stages:
  - build
  - test
  - sonar

variables:
  MAVEN_CLI_OPTS: "--batch-mode"
  SONAR_HOST_URL: "http://localhost:9000"  # Cambia por la URL real

build:
  stage: build
  image: eclipse-temurin:21-jdk
  before_script:
    - apt-get update && apt-get install -y maven
  script:
    - mvn $MAVEN_CLI_OPTS clean compile
  artifacts:
    paths:
      - target/

test:
  stage: test
  image: eclipse-temurin:21-jdk
  before_script:
    - apt-get update && apt-get install -y maven
  script:
    - mvn $MAVEN_CLI_OPTS test
  artifacts:
    when: always
    reports:
      junit: target/surefire-reports/*.xml

sonarqube:
  stage: sonar
  image: eclipse-temurin:21-jdk
  before_script:
    - apt-get update && apt-get install -y maven
  script:
    - mvn $MAVEN_CLI_OPTS verify sonar:sonar \
      -Dsonar.projectKey=mi-proyecto \
      -Dsonar.host.url=$SONAR_HOST_URL \
      -Dsonar.login=$SONAR_TOKEN
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
